export const postConstants = {
    RETRIVE_POSTS_SUCCESS: 'RETRIVE_POSTS_SUCCESS',
    RETRIVE_POSTS_FAILURE: 'RETRIVE_POSTS_FAILURE',

    FILTER_POSTS_SUCCESS: 'FILTER_POSTS_SUCCESS',
    FILTER_POSTS_FAILURE: 'FILTER_POSTS_FAILURE',

    RETRIVE_INPUTS_SUCCESS:'RETRIVE_INPUTS_SUCCESS',
    RETRIVE_INPUTS_FAILURE:'RETRIVE_INPUTS_FAILURE',

    SAVE_POST_SUCCESS:'SAVE_POST_SUCCESS',
    SAVE_POST_FAILURE:'SAVE_POST_FAILURE'

};