export const postConstants = {
    RETRIVE_POSTS_SUCCESS: 'RETRIVE_POSTS_SUCCESS',
    RETRIVE_POSTS_FAILURE: 'RETRIVE_POSTS_FAILURE',
    FILTER_POSTS_SUCCESS: 'FILTER_POSTS_SUCCESS',
    FILTER_POSTS_FAILURE: 'FILTER_POSTS_FAILURE'
};